# Generated by Django 5.0.6 on 2024-06-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_task', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
    ]
